theme: just-the-docs
title: "Ekaviran"
description: "A place to capture my thoughts and share my work."

# Enable navigation links
nav_order: 1
aux_links:
  "GitHub Repo": "https://github.com/ekaviran"
